# 언어와 jdk의 버전을 지정한다.
language: java
jdk:
  - openjdk8

# 어느 브랜치가 push 될 때 수행할지 지정한다.
# 오직 clone 브랜치가 push될 때 수행하도록 지정하였다.
branches:
  only:
    - clone

# 빌드 전에 gradlew의 권한을 추가한다.
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
# gradle을 통하여 의존성을 받게 되면 이를 캐시하여 배포할 때 마다 다시 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브랜치에 push 되면 수행되는 명령어이다.
# 프로젝트 내에 권한이 추가된 gradlew를 활용하여 clean, build를 진행한다.
script: "./gradlew clean build"

## 새롭게 추가된 부분
before_deploy:
  # 현재 위치의 모든 파일을 springboot-test로 압축한다.
  - zip -r springboot-test *
  # deploy 디렉토리를 Travis가 실행 중인 위치에 생성한다.
  - mkdir -p deploy
  # 생성한 .zip 파일을 deploy 아래로 이동한다.
  - mv springboot-test.zip deploy/springboot-test.zip

# CI 실행 완료 시 작성한 이메일로 알람
notifications:
  email:
    recipients:
      - blue6zombie6@gmail.com
