version: 0.0 # CodeDeploy 버전을 명시한다. # Make sure your AppSpec file specifies "0.0" as the version, and then try again
os: linux
files:
  - source:  / # 전체 파일을 나타낸다.
    destination: /home/ubuntu/app/zip/ # source로 지정된 전체 파일이 받을 위치이다.
    overwrite: yes # 기존 파일들이 있으면 덮어 쓸지를 결정한다.