# This is a basic workflow to help you get started with Actions

name: Spring Boot & Gradle CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the clone branch
  push:
    branches: [ clone ]
  pull_request:
    branches: [ clone ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Task sequence
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
          
      - name: Grant execute permission
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew clean build
        
      # 전송할 파일을 담은 directory 형성
      - name: Make Directory for deliver
        run: mkdir deploy
        
      # Jar file copy
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/
        
      # 압축파일 형태로 전달(traffic 아끼기?)
      - name: Make zip file
        run: zip -r -qq -j ./sixzombiesbucket.zip ./deploy

      # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \ 
	  ./sixzombiesbucket.zip s3://sixzombiesbucket/
